apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.dockerRegistry.enabled }}
    - port: {{ .Values.dockerRegistry.port }}
      targetPort: docker
      protocol: TCP
      name: docker
    - port: 8083
      targetPort: docker-alt
      protocol: TCP
      name: docker-alt
    {{- end }}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}